//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakt5
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginData
    {
        public int LoginData_id { get; set; }
        public string Loqin { get; set; }
        public string Passwordd { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
