//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakt5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int warehouse_id { get; set; }
        public System.DateTime DateOfReceipt { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> suppliers_id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Product Product { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
